export const createRecipe = {
  'createRecipe.title': 'Title',
  'createRecipe.apetizer': 'Apetizer',
  'createRecipe.bread': 'Bread',
  'createRecipe.firstCourse': 'First Course',
  'createRecipe.secondCourse': 'Second Course',
  'createRecipe.salad': 'Salad',
  'createRecipe.sideDish': 'Side dish',
  'createRecipe.snack': 'Snack',
  'createRecipe.dessert': 'Dessert',
  'createRecipe.soup': 'Soup',
  'createRecipe.sauce': 'Sauce',
  'createRecipe.category': 'Category',
  'createRecipe.save': 'Save',
  'createRecipe.saving': 'Saving',
};
