export const createRecipe = {
  'createRecipe.name': 'Name',
  'createRecipe.title': 'Create Recipe',
  'createRecipe.apetizer': 'Apetizer',
  'createRecipe.bread': 'Bread',
  'createRecipe.firstCourse': 'First Course',
  'createRecipe.secondCourse': 'Second Course',
  'createRecipe.salad': 'Salad',
  'createRecipe.sideDish': 'Side dish',
  'createRecipe.snack': 'Snack',
  'createRecipe.dessert': 'Dessert',
  'createRecipe.soup': 'Soup',
  'createRecipe.sauce': 'Sauce',
  'createRecipe.category': 'Category',
  'createRecipe.save': 'Save',
  'createRecipe.saving': 'Saving',
  'createRecipe.notSelected': 'Not Selected',
  'createRecipe.categoryRequired': 'The category is required',
  'createRecipe.nameRequired': 'The name is required',
  'createRecipe.numberOfServings': 'Number of servings',
  'createRecipe.cookingTime': 'Cooking time',
  'createRecipe.preparationTime': 'Preparation time',
  'createRecipe.preparationTimeRequired': 'The preparation time is required',
  'createRecipe.cookingTimeRequired': 'The cooking time is required',
  'createRecipe.numberOfServingsRequired': 'The number of servings is required',
};
