export const createRecipe = {
  'createRecipe.name': 'Nome',
  'createRecipe.title': 'Crea Ricetta',
  'createRecipe.apetizer': 'Antipasto',
  'createRecipe.bread': 'Pane',
  'createRecipe.firstCourse': 'Primo',
  'createRecipe.secondCourse': 'Secondo',
  'createRecipe.salad': 'Insalata',
  'createRecipe.sideDish': 'Contorno',
  'createRecipe.snack': 'Snack',
  'createRecipe.dessert': 'Dolce',
  'createRecipe.soup': 'Zuppa',
  'createRecipe.sauce': 'Salsa',
  'createRecipe.category': 'Categoria',
  'createRecipe.save': 'Salva',
  'createRecipe.saving': 'Salvando...',
  'createRecipe.notSelected': 'Nessuna',
  'createRecipe.categoryRequired': 'La categoria deve essere selezionata',
  'createRecipe.nameRequired': 'La ricetta deve avere un nome',
  'createRecipe.numberOfServings': 'Numero di porzioni',
  'createRecipe.cookingTime': 'Tempo di cottura',
  'createRecipe.preparationTime': 'Tempo di preparazione',
  'createRecipe.preparationTimeRequired':
    'Il tempo di preparazione dve essere inserito',
  'createRecipe.cookingTimeRequired': 'Il tempo di cottura dve essere inserito',
  'createRecipe.numberOfServingsRequired':
    'Il numero di porzioni dve essere inserito',
};
