export const createRecipe = {
  'createRecipe.name': 'Namn',
  'createRecipe.title': 'Skapa Recept',
  'createRecipe.apetizer': 'Förrätt',
  'createRecipe.bread': 'Bröd',
  'createRecipe.firstCourse': 'Först',
  'createRecipe.secondCourse': 'Andra',
  'createRecipe.salad': 'Sallad',
  'createRecipe.sideDish': 'Sidorätt',
  'createRecipe.snack': 'Snack',
  'createRecipe.dessert': 'Efterrätt',
  'createRecipe.soup': 'Soppa',
  'createRecipe.sauce': 'Sås',
  'createRecipe.category': 'Kategori',
  'createRecipe.save': 'Spara',
  'createRecipe.saving': 'Sparar...',
  'createRecipe.notSelected': 'Ej vald',
  'createRecipe.categoryRequired': 'Kategori måste väljas',
  'createRecipe.nameRequired': 'Namn måste sättas',
  'createRecipe.numberOfServings': 'Antal portioner',
  'createRecipe.cookingTime': 'Tillagningstid',
  'createRecipe.preparationTime': 'Förberedelsetid',
  'createRecipe.preparationTimeRequired': 'Tillagningstiden måste sättas',
  'createRecipe.cookingTimeRequired': 'Förberedelsetiden måste sättas',
  'createRecipe.numberOfServingsRequired': 'Antal portionerna måste sättas',
};
